### ISSUE TITLE
Server Error 401: Unable to generate Access Token

### ISSUE THREAD

**Issue by mail2chromium** [NHSDigital/hello-world-auth-examples#26]
Dear team, 

I am currently working on an Android Project to get Patient details based on its Patient-ID. To get an access token for the user-restricted API, I am using your provided Java Tutorial based on the following GitHub repository;

I have carefully followed all of these steps;

1.	Create a [JWKS](https://datatracker.ietf.org/doc/html/rfc7517) endpoint to publicly host your public key and note the URL.
2.	Navigate to [my developer account](https://portal.developer.nhs.uk/) and sign in.
3.	Select 'My applications' and 'Manage your applications'.
4.	Select the application you want to add your JWKS endpoint to.
5.	Enter the URL of your JWKS endpoint and click Save.

Reference Links:

1. The [Personal Demographics Service - FHIR API](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir) is a [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest) API and as such uses the [Application-restricted RESTful APIs - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication) access mode

2. Can I refer you to Step 3 on the page [Application-restricted RESTful APIs - signed JWT authentication - NHS Digital](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication#step-3-register-your-public-key-with-us).

I am somewhat able to get JWT based on all the required parameters such as 

```
        String PRIVATE_KEY_PATH = ""; // Current Directory
        String TOKEN_URL = "https://sandbox.api.service.nhs.uk/oauth2/token";
        String CLIENT_ID = "APPLICATION_ID"; // From my NHS Developer account
        String KID = "test-2";
        String ENDPOINT = "https://sandbox.api.service.nhs.uk/hello-world/hello/application";
```
I am attaching the screenshot of my implementation and where I am getting this issue; 

![image](https://user-images.githubusercontent.com/42235538/189988084-6980ac0f-1c2f-4a40-a6b3-7bdf9e359e3e.png)

But I am now getting 401 server error from the NHS server side. I am using windows OS but as I am using Android Studio, so I am a bit confused that which of the following files can be used, as I am getting weird errors for different files;

I have given the following files one by one and getting strange errors;
**For jwtRS512.pub**:

```
 unable to convert key pair: Attempt to invoke virtual method 'org.bouncycastle.asn1.pkcs.PrivateKeyInfo org.bouncycastle.openssl.PEMKeyPair.getPrivateKeyInfo()' on a null object reference
```

**For jwtRS512.key.pub**:

```
 -> org.bouncycastle.asn1.x509.SubjectPublicKeyInfo cannot be cast to org.bouncycastle.openssl.PEMKeyPair
```

**For jwtRS512**: 

```
 {"fault":{"faultstring":"Failed to parse key: policy(VerifyJWT.ClientCredentials)","detail":{"errorcode":"steps.jwt.KeyParsingFailed"}}}
```

I have tried all the possible files which are being generated using your methodology. I am getting the above errors with the recommended files.

**TOOLS:**

1. Operating System Windows 10-11
2. Android Studio 2021.2.1 Patch 2 for Windows 64-bit
3. Android Application API Level - 9

I am very near to solving my issue, your quick assistance might save me days.

**Comment by artronics** [comment]
@mail2chromium we created a ticket to look into this issue.

**Comment by artronics** [comment]
@mail2chromium Sorry for the delay. Do you still have this issue? I need someone to replicate it on windows but meanwhile:
* You need to use your private key for signing JWT. i.e `jwtRS512`
* `PRIVATE_KEY_PATH` must be the **absolute** path to the file. Not the directory.
* I can confirm the key-pair tutorial works for Linux. If you want to try it on linux you can use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). I had issues with openssl on Windows before. WSL will allow you to run Linux on your Windows machine. 
You can also quickly follow our Linux tutorial by running Ubuntu docker:
```
 docker run -it --rm ubuntu
```
After running above command you get access to a running ubuntu container. 
```
# You need to install openssl and openssh-client
apt update && apt install openssl openssh-client -y
```
Now you can follow the linux tutorial. You also need to attach a volume to your container so you can access the generated files from you windows machine.

**Comment by artronics** [comment]
@mail2chromium I tried to reproduce your JWT issue on a Windows 10 machine. Here is my finding.
I encounter no issue when following the tutorial on a windows machine so, I tried different ways to see if I can reproduce your errors.

* It's likely that you created your private key with a passphrase. When I created a private key this way, I got ` threw exception; nested exception is java.lang.ClassCastException: class org.bouncycastle.openssl.PEMEncryptedKeyPair cannot be cast to class org.bouncycastle.openssl.PEMKeyPair` 
You encounter this exception as well however, you got this exception when you passed your public key instead of private key. As I mentioned on my previous comment, you need to pass your private key.
* Judging by the error that you get when you pass your private key (that's it `jwtRS512`) I would say your private key is fine and the error is coming from server. This means there is probably a misconfiguration.

I can look at your config and code in a google meet call. **Please let us know otherwise I'll close this issue within 10 days.** 
Thanks.

**Comment by mail2chromium** [comment]
@artronics Thanks for your response.

Actually, I am developing an Android Application for smart glasses. So, my development is dependent on Java/kotlin for Android Studio and C#/C++ for Unity.

Can you please suggest to me something which is useful for Android Studio?
If I generate the signing keys using the windows platform, how can I use them for Android studio?

If you are available for a google meet call, it would be really helpful. How can we proceed with the meeting this week?

Kind regards,

**Comment by artronics** [comment]
I'm not sure if you received my message from github provided email address. Here is a [google doc ](https://docs.google.com/document/d/1cG7bN9aK2Z72RX5WXLVCkulvJpSvY6WWqQxVc4F91oI/edit?usp=sharing)containing my email address. Please send me an email if you are still intrested.

**Comment by JalfResi** [comment]
@mail2chromium - I'm going to close this issue. If you have any further questions please reach out to us directly via the channels included in our emails.
